<a href="https://colab.research.google.com/github/SairamTadepalli19/Day1_ML/blob/main/Day1_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 # **Numpy**

In [ ]:
# Is for mathematical operations

import numpy as np

a = [1,2,3,4,5]

arr1 = np.array(a)

b = [[1,2,3,4], [5,6,7,8]]

arr2 = np.array(b)

print(arr1)
print(arr2)



[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(type(a),
type(arr1),
type(b),
type(arr2),)

<class 'list'> <class 'numpy.ndarray'> <class 'list'> <class 'numpy.ndarray'>


In [ ]:
import sys

s = range(1000)

print("Size of each elements in the list in bytes", sys.getsizeof(s))

print("Complete list size in bytes", sys.getsizeof(s) * len(s))

Size of each elements in the list in bytes 48
Complete list size in bytes 48000


In [ ]:
#We are checking comparison between numpy size and nomral size of "sys" package

import numpy as np

s = np.arange(1000)

print("Size of each elements in the list by bytes", s.itemsize)

print("Complete list size in bytes", s.size * s.itemsize)


Size of each elements in the list by bytes 8
Complete list size in bytes 8000


In [ ]:
#Import time library and make execution time taking by the system

import time

a = range(1000) # [0 ... 999]
b = range(1000) # [0 ... 999]

start = time.time()

ab = [(a * b) for a,b in zip(a,b)] #List Comprehension

# Creating a concised form of complete list and for loop or any other conditional statements

end = time.time()

print("Total time taken", end - start)



Total time taken 0.00019979476928710938


In [ ]:
import numpy
import time
arr1 = np.arange(1000)
arr2 = np.arange(1000)

start = time.time()

arr_mul = arr1 * arr2

end = time.time()

print("Total time taken", end - start)

Total time taken 0.0007355213165283203


In [ ]:
lst1 = [1,2,3,4]

arr = np.array(lst1)

print(arr)

[1 2 3 4]


In [ ]:
print(lst1 + 1)

TypeError: ignored

In [ ]:
print(arr + 1)

[2 3 4 5]


In [1]:
import numpy as np
arr1 = np.array([1,2,3])

print(arr1)

[1 2 3]


In [2]:
type(arr1)

numpy.ndarray

In [3]:
arr2 = np.zeros((2,2))

print(arr2)

[[0. 0.]
 [0. 0.]]


In [4]:
lst1 = [1,2,3,4.52, True, False, 2+3j, "Codegnan"]

print(lst1)

[1, 2, 3, 4.52, True, False, (2+3j), 'Codegnan']


In [5]:
type(lst1)

list

In [6]:
#4 Different types of data structures in python

# list - []

# Tuple - ()

# Dictionary - {Key : Value}

# Set - {Numerical values and unique variables}

In [7]:
# Creating an n-dimensional array

a = [[1,2,3], [4,5,6]]

print(a)

[[1, 2, 3], [4, 5, 6]]


In [8]:
import numpy as np

np.array(a, ndmin = 10)

array([[[[[[[[[[1, 2, 3],
               [4, 5, 6]]]]]]]]]])

In [9]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
arr [2,0]

7

In [11]:
arr[3,0]

IndexError: ignored

In [13]:
np.arange(2,2,0)

ZeroDivisionError: ignored

In [14]:
#Numpy - Is for mathematical operations. Like creating and manipulating arrays and numbers

# Pandas - Is the data handling mechanism and tool. Which can handle the datasets to process into models


In [15]:
np.random.rand(3,2)

array([[0.81878112, 0.75095388],
       [0.27857995, 0.87609001],
       [0.93440918, 0.15105175]])

In [17]:
arr1 = np.random.rand(3,2)

arr2 = np.random.rand(3,2)

sum1 = np.add(arr1, arr2)

print(arr1)
print(arr2)
print(sum1)

[[0.45302177 0.06807193]
 [0.54562794 0.70338343]
 [0.58325714 0.64566701]]
[[0.29024117 0.80387474]
 [0.29153946 0.7441946 ]
 [0.44016619 0.58408923]]
[[0.74326294 0.87194667]
 [0.8371674  1.44757803]
 [1.02342332 1.22975624]]


In [19]:
sub1 = np.subtract(arr1,arr2)

print(sub1)

[[ 0.1627806  -0.73580282]
 [ 0.25408848 -0.04081118]
 [ 0.14309095  0.06157779]]


In [22]:
# Indexing and slicing

a = [1,2,5,7,20.5,"Codegnan", True]

a [5]

'Codegnan'

In [23]:
a[8]

IndexError: ignored

In [25]:
# Slicing = [start: end+1]

a [0:6]

[1, 2, 5, 7, 20.5, 'Codegnan']

In [26]:
a[-1]

True

In [27]:
a[-2]

'Codegnan'

In [28]:
a[:5]

[1, 2, 5, 7, 20.5]

In [29]:
a = [1,2,5,7,20.5,"Codegnan", True]

In [30]:
a[-6:-1]

[2, 5, 7, 20.5, 'Codegnan']

In [31]:
a = [1,2,5,7,20.5,"Codegnan", True,1,2,5,7,20.5,"Codegnan", True,1,2,5,7,20.5,"Codegnan", True]

a[0:10:2]

[1, 5, 20.5, True, 2]

In [32]:
a.reverse()

In [33]:
a


[True,
 'Codegnan',
 20.5,
 7,
 5,
 2,
 1,
 True,
 'Codegnan',
 20.5,
 7,
 5,
 2,
 1,
 True,
 'Codegnan',
 20.5,
 7,
 5,
 2,
 1]

In [35]:
#The skip value will take start and end+1 variables and we are skipping values in between
a = [1,2,5,7,20.5,"Codegnan", True,1,2,5,7,20.5,"Codegnan", True,1,2,5,7,20.5,"Codegnan", True]

a[0:10:3]


[1, 7, True, 5]

In [38]:
# Reshape an array

arr2 = np.array([[1,2,3,4],
         [5,6,7,8]])

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
arr2.shape

(2, 4)

In [40]:
arr2.reshape(1,8)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

## Pandas - Data Handling mechanism. We need to upload a dataset and get the link to read the dataset

In [41]:
import pandas as pd

In [42]:
#Read the dataset using pandas

# We have a function read_csv() to read any csv file

# CSV - Commo Seperate Values


#We have plenty number of file reading mechanisms in pandas

# we can read excel sheet, database files with different reading formats

data = pd.read_csv("/content/ipl_matches.csv")

In [44]:
data.head(10)

id  season       city  ...         umpire1        umpire2 umpire3
0   1    2017  Hyderabad  ...     AY Dandekar       NJ Llong     NaN
1   2    2017       Pune  ...  A Nand Kishore         S Ravi     NaN
2   3    2017     Rajkot  ...     Nitin Menon      CK Nandan     NaN
3   4    2017     Indore  ...    AK Chaudhary  C Shamshuddin     NaN
4   5    2017  Bangalore  ...             NaN            NaN     NaN
5   6    2017  Hyderabad  ...      A Deshmukh       NJ Llong     NaN
6   7    2017     Mumbai  ...     Nitin Menon      CK Nandan     NaN
7   8    2017     Indore  ...    AK Chaudhary  C Shamshuddin     NaN
8   9    2017       Pune  ...     AY Dandekar         S Ravi     NaN
9  10    2017     Mumbai  ...     Nitin Menon      CK Nandan     NaN

[10 rows x 18 columns]

In [46]:
# If you want to retrieve last 5 or last 10 rows. Then use tail() function

data.tail()

id  season       city  ...          umpire1          umpire2 umpire3
631  632    2016     Raipur  ...   A Nand Kishore     BNJ Oxenford     NaN
632  633    2016  Bangalore  ...     AK Chaudhary  HDPK Dharmasena     NaN
633  634    2016      Delhi  ...        M Erasmus    C Shamshuddin     NaN
634  635    2016      Delhi  ...        M Erasmus        CK Nandan     NaN
635  636    2016  Bangalore  ...  HDPK Dharmasena     BNJ Oxenford     NaN

[5 rows x 18 columns]

In [47]:
data.tail(10)

id  season  ...          umpire2 umpire3
626  627    2016  ...        CK Nandan     NaN
627  628    2016  ...     BNJ Oxenford     NaN
628  629    2016  ...      Nitin Menon     NaN
629  630    2016  ...        CK Nandan     NaN
630  631    2016  ...        M Erasmus     NaN
631  632    2016  ...     BNJ Oxenford     NaN
632  633    2016  ...  HDPK Dharmasena     NaN
633  634    2016  ...    C Shamshuddin     NaN
634  635    2016  ...        CK Nandan     NaN
635  636    2016  ...     BNJ Oxenford     NaN

[10 rows x 18 columns]

In [48]:
#Check the shape

data.shape

(636, 18)

In [49]:
data.info() #information regarding the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 636 entries, 0 to 635
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   id               636 non-null    int64  
 1   season           636 non-null    int64  
 2   city             629 non-null    object 
 3   date             636 non-null    object 
 4   team1            636 non-null    object 
 5   team2            636 non-null    object 
 6   toss_winner      636 non-null    object 
 7   toss_decision    636 non-null    object 
 8   result           636 non-null    object 
 9   dl_applied       636 non-null    int64  
 10  winner           633 non-null    object 
 11  win_by_runs      636 non-null    int64  
 12  win_by_wickets   636 non-null    int64  
 13  player_of_match  633 non-null    object 
 14  venue            636 non-null    object 
 15  umpire1          635 non-null    object 
 16  umpire2          635 non-null    object 
 17  umpire3         

In [50]:
#Description of this dataset

data.describe()


id       season  ...  win_by_wickets  umpire3
count  636.000000   636.000000  ...      636.000000      0.0
mean   318.500000  2012.490566  ...        3.372642      NaN
std    183.741666     2.773026  ...        3.420338      NaN
min      1.000000  2008.000000  ...        0.000000      NaN
25%    159.750000  2010.000000  ...        0.000000      NaN
50%    318.500000  2012.000000  ...        4.000000      NaN
75%    477.250000  2015.000000  ...        7.000000      NaN
max    636.000000  2017.000000  ...       10.000000      NaN

[8 rows x 6 columns]

In [70]:
#We are using html parser to access data from a webpage and read the content in that web page

web = pd.read_html("https://en.wikipedia.org/wiki/States_and_union_territories_of_India")[3]

In [71]:
web.head()

State  ... Additional officiallanguages[39]
0     Andhra Pradesh  ...                                —
1  Arunachal Pradesh  ...                                —
2              Assam  ...                    Bengali, Bodo
3              Bihar  ...                             Urdu
4       Chhattisgarh  ...                    Chhattisgarhi

[5 rows x 11 columns]

In [65]:
excel = pd.read_excel("/content/ex1.xlsx")

In [66]:
web

State  ...                   Additional officiallanguages[39]
0      Andhra Pradesh  ...                                                  —
1   Arunachal Pradesh  ...                                                  —
2               Assam  ...                                      Bengali, Bodo
3               Bihar  ...                                               Urdu
4        Chhattisgarh  ...                                      Chhattisgarhi
5                 Goa  ...                                            Marathi
6             Gujarat  ...                                                  —
7             Haryana  ...                                    Punjabi[41][42]
8    Himachal Pradesh  ...                                       Sanskrit[44]
9           Jharkhand  ...  Angika, Bengali, Bhojpuri, Ho, Kharia, Khortha...
10          Karnataka  ...                                                  —
11             Kerala  ...                                        English[46]
12     Madhya Pradesh  ...                                                  —
13        Maharashtra  ...                                                  —
14            Manipur  ...                                            English
15          Meghalaya  ...                                           Khasi[a]
16            Mizoram  ...                                                  —
17           Nagaland  ...                                                  —
18             Odisha  ...                                                  —
19             Punjab  ...                                                  —
20          Rajasthan  ...                                            English
21             Sikkim  ...  Bhutia, Gurung, Lepcha, Limbu, Manggar, Mukhia...
22         Tamil Nadu  ...                                            English
23          Telangana  ...                                           Urdu[49]
24            Tripura  ...                                                  —
25      Uttar Pradesh  ...                                               Urdu
26        Uttarakhand  ...                                       Sanskrit[51]
27        West Bengal  ...        Hindi, Odia, Telugu, Punjabi, Santali, Urdu

[28 rows x 11 columns]

In [67]:
excel.head()

Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo